<?php
/**
 * @file cute_slider.install
 * User: duynguyen
 * Date: 3/30/13
 * Time: 12:06 PM
 * To change this template use File | Settings | File Templates.
 */


/**
 * Implements hook_uninstall()
 */
function cute_slider_uninstall() {
  # Delete file default_background.jpg
  $public_folder = variable_get('file_public_path', conf_path() . '/files');
  unlink($public_folder . '/cute_slider_default_background.jpg');

  # Remove templates variable
  variable_del('cute_slider_templates');
}